#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new \Paxal\FFITest\RandomValueCommand());
$application->add(new \Paxal\FFITest\UnfinalCommand());
$application->run();
